version: "3.8"
services:
  bot:
    image: "biggarik/anna_nihongo_bot:latest"
    container_name: ${BOT_NAME:-bot}
    restart: unless-stopped
    env_file:
      - ${ENV_FILE:-.env}
    networks:
      - bot-network

networks:
  bot-network:
    name: ${NETWORK_NAME:-bot-network}
    driver: bridge