version: "3.8"
services:
  bot:
    image: "biggarik/anna_nihongo_bot:latest"
    container_name: ${BOT_NAME:-bot}
    restart: unless-stopped
    env_file:
      - ${ENV_FILE:-.env}
    networks:
      - bot-network
    volumes:
      - ./bot-96c6f518f0cd.json:/app/bot-96c6f518f0cd.json

networks:
  bot-network:
    name: ${NETWORK_NAME:-bot-network}
    driver: bridge