version: "3.8"
services:
    bot:
        # image: "biggarik/anna_nihongo_bot:latest"
        image: "anna_nihongo_bot:latest"
        restart: "unless-stopped"
        # внутри контейнера по адресу host.docker.internal (имя можно указать любое по желанию) ему [контейнеру]
        # будут доступны процессы на хосте.
        extra_hosts:
          - "host.docker.internal:host-gateway"
        env_file: ".env"
        depends_on:
          - "redis_fsm"
    redis_fsm:
        image: "redis:7"
        restart: "unless-stopped"
        volumes:
          # Подменяем файл конфигурации внутри контейнера на свой
          - "./redis/data/redis.conf:/usr/local/etc/redis/redis.conf"
          # Примонтируем внутрь контейнера наш каталог в расположение /data
          - "./redis/data:/data"
        command: "redis-server /usr/local/etc/redis/redis.conf"
        healthcheck:
            test: [ "CMD", "redis-cli","ping" ]