version: "3.8"
services:
    bot:
        image: "biggarik/anna_nihongo_bot:latest"
        restart: "unless-stopped"
        env_file: ".env"
        depends_on:
          - "redis_fsm"
    redis_fsm:
        image: "redis:7"
        restart: "unless-stopped"
        volumes:
          # Подменяем файл конфигурации внутри контейнера на свой
          - "/d/Projects/redis/data/redis.conf:/usr/local/etc/redis/redis.conf"
          # Примонтируем внутрь контейнера наш каталог в расположение /data
          - "/d/Projects/redis/data:/data"
        command: "redis-server /usr/local/etc/redis/redis.conf"
        healthcheck:
            test: [ "CMD", "redis-cli","ping" ]