version: 1
disable_existing_loggers: False

formatters:
  default:
    format: '#%(levelname)-8s %(name)s:%(funcName)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

  formatter_stderr:
    format: '[%(asctime)s] #%(levelname)-8s %(filename)s:%(lineno)d - %(name)s:%(funcName)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

  formatter_stdout:
    format: '#%(levelname)-8s [%(asctime)s] - %(filename)s:%(lineno)d - %(name)s:%(funcName)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

  formatter_file:
    format: '[%(asctime)s] - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

filters:
  critical_filter:
    (): filters.log_filters.CriticalLogFilter

  error_filter:
    (): filters.log_filters.ErrorLogFilter

  debug_warning_filter:
    (): filters.log_filters.DebugWarningLogFilter

  info_file_filter:
    (): filters.log_filters.InfoFileLogFilter

handlers:
  default:
    class: logging.StreamHandler
    formatter: default

  stderr:
    class: logging.StreamHandler
    formatter: formatter_stderr

  stdout:
    class: logging.StreamHandler
    formatter: formatter_stdout
    stream: ext://sys.stdout

  info_file:
    class: logging.FileHandler
    filename: 'user.log'
    mode: 'a'
    formatter: formatter_file
    filters: [info_file_filter]

loggers:
  __main__:
    level: INFO
    handlers: [stderr]
    propagate: False

  handlers.user_handlers:
    level: INFO
    handlers: [info_file, stdout]
    propagate: False

  visualizer:
    level: INFO
    handlers: [stderr]
    propagate: False

  voice_recognizer:
    level: INFO
    handlers: [stderr]
    propagate: False

root:
  level: INFO
  formatter: default
  handlers: [default]